name: Controlar flujo ejecucion

on:
  workflow_dispatch:
    inputs:
      pass-unit-tests:
        description: funcion test
        type: boolean
        default: false
        required: true

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: Lint and build
        run: echo "Linting and building project"

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Running unit tests
        run: echo "Corriendo unit test..."
      - name: Faling tests
        if: ${{!inputs.pass-unit-tests}}
        continue-on-error: true
        run: exit 1

  deploy-nonprod:
    runs-on: ubuntu-latest
    needs: 
      - lint-build
      - unit-test
    steps:
      - name: Deploying to nonprod
        run: echo "Deploying to nonprod"